# Generated by Django 4.2.3 on 2023-08-19 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_mangas', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Mangas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('created', models.DateField()),
                ('book_photo', models.FileField(upload_to='mangas_photo/', verbose_name='Фото манги')),
                ('book_description', models.TextField(max_length=2000)),
                ('book_pdf', models.FileField(upload_to='mangas_pdf')),
                ('author_manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_manga', to='authors.authors')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_manga', to='manga.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_mangas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Манга',
                'verbose_name_plural': 'Манги',
            },
        ),
    ]
